#!/usr/bin/env python3
"""Generate the seeded milestone ledger and decision records from plan v0.1 data.
Run from repo root: python scripts/gen_seed.py
Idempotent: overwrites generated files. Source of truth for seed content."""
import os, re, json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

KIND = {"s": "step", "d": "decision", "r": "ratification", "g": "gate", "p": "practice"}

L = [
{"i":"D1","k":"d","w":"D","t":"front-end framework","pl":"Which tool builds the member portal.","o":"organizers","dep":[],"dec":[],"v":"human:organizers","su":"A framework is chosen against the PRD criteria and recorded in docs/decisions/D1.md.","b":"PRD criteria: portability, accessibility, mobile-first, Supabase compatibility, design-system fidelity, plus the chokepoint test (CIS \u00a717). Proposed default: a static-first framework with islands of interactivity (Astro is the type specimen; Vite + React SPA is the alternative)."},
{"i":"D2","k":"d","w":"D","t":"application form host","pl":"Where the public application form lives.","o":"organizers","dep":[],"dec":[],"v":"human:organizers","su":"A form path is chosen and recorded in docs/decisions/D2.md.","b":"The PRDs frame Formbricks (self-host) versus Tally or Typeform (managed chokepoint) (Hub \u00a711). The constraint adds a third option, named explicitly as an extension: a static form on Pages inserting through a narrowly scoped anonymous RLS policy. Proposed default: the native path, Formbricks as fallback."},
{"i":"D3","k":"d","w":"D","t":"repository visibility and naming","pl":"Whether the repository is public from day one.","o":"organizers","dep":[],"dec":[],"v":"human:organizers","su":"Org and repo exist with a recorded visibility decision in docs/decisions/D3.md.","b":"Proposed default: public from first commit, the O-pathway Phase 01 commitment made literal (CIS \u00a704). Hard rule either way: no secrets, no member PII, synthetic seeds only."},
{"i":"D4","k":"d","w":"D","t":"transactional email provider","pl":"Which service delivers official email.","o":"organizers","dep":[],"dec":[],"v":"human:organizers","su":"One provider with API send and delivery webhooks is chosen and recorded in docs/decisions/D4.md.","b":"Required because notices carry legally timed windows and delivery tracking (CIS \u00a708, draft-bylaws \u00a72.4); Supabase built-in mail covers auth flows only. Candidate class: Resend, Postmark, SES; no endorsement implied."},
{"i":"D5","k":"d","w":"D","t":"make.com adoption trigger","pl":"Whether Make.com is ever adopted, and what would justify it.","o":"organizers","dep":[],"dec":[],"v":"human:organizers","su":"The reversal trigger is recorded in the chokepoint analysis and docs/decisions/D5.md.","b":"Proposed default: not adopted in alpha. Trigger if invoked: a required integration whose first-party Edge Function cost exceeds reasonable effort and whose data remains exportable. Until then its PRD duties route to pg_cron, Edge Functions, and Actions."},
{"i":"D6","k":"d","w":"D","t":"alpha access posture","pl":"Whether a publicly visible app shell is acceptable for the alpha.","o":"organizers","dep":[],"dec":[],"v":"human:organizers","su":"The posture is recorded in docs/decisions/D6.md; W0.12 exposure follows it.","b":"Proposed default: accept the public static shell; privacy enforced at the data layer; noindex; invite-only auth. Alternative augmentation: a proxy with access control in front of Pages."},
{"i":"D7","k":"d","w":"D","t":"section addressing scheme","pl":"How we cite bylaw sections before ratification.","o":"organizers + counsel awareness","dep":[],"dec":[],"v":"human:organizers","su":"The draft-bylaws: prefix register exists in docs/citations.md and is recorded in docs/decisions/D7.md.","b":"Pre-ratification, every citation uses the draft-bylaws:\u00a7x.y prefix against a register; ratification (R1) triggers one sweep that drops the prefix and freezes addresses. Keeps cite-as-you-enforce honest before the text is final."},
{"i":"D8","k":"d","w":"D","t":"attestation scope and key custody","pl":"Which events go on-chain, and who holds the keys.","o":"working group (CIS \u00a717)","dep":[],"dec":[],"v":"human:working-group","su":"Scope and custody recorded in docs/decisions/D8.md; blocks only optional attestation extensions.","b":"Deferred beyond alpha. Blocks the optional attestation steps in W4 and W6 only."},
{"i":"D9","k":"d","w":"D","t":"EE liaison interface form","pl":"How the Ethereum Everywhere liaison reviews KPIs.","o":"organizers + EE team","dep":[],"dec":[],"v":"human:organizers","su":"Dashboard, digest, or shared page is chosen and recorded in docs/decisions/D9.md.","b":"CROPS implications cut both ways (Hub \u00a711). Proposed default: scoped read-only dashboard credential, with the public KPI view satisfying the open-source pull."},
{"i":"D10","k":"d","w":"D","t":"lease-entity question","pl":"Which entity holds the third-floor lease.","o":"board","dep":[],"dec":[],"v":"human:board","su":"Leaseholder recorded in docs/decisions/D10.md; facility obligations enter the ledger accordingly.","b":"Whether West or the LCA holds the lease affects how facility obligations enter the ledger (CIS \u00a717). Blocks specific W3.6 detail only; indexed so the dependency is visible."},
{"i":"R1","k":"r","w":"R","t":"bylaws ratification","pl":"Counsel and membership ratify the bylaws.","o":"counsel + membership","dep":[],"dec":[],"act":["W3.0","W4.0"],"v":"counsel","su":"Bylaws ratified; citation freeze sweep run; \u00a718.1 semantics final.","b":"Named reviewers: Pote Law Firm, Yev Muchnik. Activates allocation-formula automation (until then manual entry against the equal default, exactly as CIS \u00a717 specifies), the D7 citation sweep, and binding electronic votes. Blocks no build step."},
{"i":"R2","k":"r","w":"R","t":"hub membership agreement","pl":"Counsel ratifies the Hub Membership Agreement.","o":"counsel","dep":[],"dec":[],"act":["W2.1"],"v":"counsel","su":"Agreement ratified; Hub Member role activates against it.","b":"Pote review per Hub \u00a711. Until ratified, Hub access proceeds against the interim acceptable-use policy, itself recorded in the agreements repository so the interim state is on the record."},
{"i":"W0.1","k":"s","w":"W0","t":"repo bootstrap and governance","pl":"Create the shared repository and write down its rules.","o":"human (admin) + agent","dep":[],"dec":["D3"],"v":"ci:repo-policy","su":"Repository exists with README, GOVERNANCE.md, CODEOWNERS, PR and issue templates, branch protection applied; ci:repo-policy green.","b":"The repo is the milestone system, so its own governance files are the first artifact. Human creates org and repo per D3 and applies protection; agent commits the governance files and the repo-policy check that asserts their presence and the protection settings via API read."},
{"i":"W0.2","k":"s","w":"W0","t":"ledger scaffold, validator, status board","pl":"Turn this plan into live, checkable files that track themselves.","o":"agent","dep":["W0.1"],"dec":[],"v":"ci:milestone-validate","su":"All ledger entries exist as schema-valid files; validator enforces acyclicity and gating; STATUS.md and index.json regenerate on push.","b":"Converts the plan into the live ledger: validator scripts, status generator, the workflow, and one milestone file per entry. A PR that changes code without touching a milestone file fails validation; that rule keeps the ledger exhaustive. The repo seed (this collection) supplies the schema, the validator, and the seeded files; this step lands them in the live repository and wires the workflow."},
{"i":"W0.3","k":"s","w":"W0","t":"supabase project provisioning","pl":"Stand up the database account and connect it safely.","o":"human (credentials) + agent","dep":["W0.1"],"dec":[],"v":"ci:db-verify (connection)","su":"Hosted project linked; access token, project ref, anon and service keys present as Actions secrets; ci:db-verify can connect.","b":"One hosted project is production-of-record; local development via CLI; secrets never enter the repo. Human creates the project and stores secrets per docs/SECRETS.md; agent commits config and the connection stage of db-verify."},
{"i":"W0.4","k":"s","w":"W0","t":"migration pipeline and shadow verification","pl":"Every database change passes a rehearsal before it touches the real thing.","o":"agent","dep":["W0.3"],"dec":[],"v":"ci:db-verify","su":"CI applies all migrations to a clean shadow database and runs pgTAP; push to hosted occurs only from main after green.","b":"With a single hosted environment, the shadow apply is the safety net. Migrations are append-only; no manual SQL against production. Conventions in docs/CONVENTIONS.md govern naming and structure."},
{"i":"W0.5","k":"s","w":"W0","t":"auth: invite-only identity layer","pl":"Sign-in by email, invitation only.","o":"agent","dep":["W0.4"],"dec":["D6"],"v":"ci:rls-audit (auth probes)","su":"Email OTP sign-in works; non-allowlisted sign-up is rejected; JWT carries role claims from the auth hook; probe test proves all three.","b":"Identity is the CIS identity layer (CIS \u00a707); alpha is invite-only per D6. Invites table, before-user-created hook rejecting non-invited addresses, custom-claims hook stamping roles from the registry (W0.8 extends)."},
{"i":"W0.6","k":"s","w":"W0","t":"RLS baseline: default-deny, cite-as-you-enforce","pl":"Lock every table by default; each access rule cites the bylaw line that permits it.","o":"agent","dep":["W0.4"],"dec":["D7"],"v":"ci:rls-audit","su":"Every public table has RLS enabled and forced; every policy carries a citation comment matching the D7 register; anonymous and cross-member probe suites return denial on protected tables.","b":"The whole authorization perimeter under the public anon key. Migration template forces RLS on creation; policy comments embed draft-bylaws or grant citations per docs/CONVENTIONS.md; pgTAP audits coverage and comment format; probe suite executes as anon and as a second member. This CI job is a required check forever after."},
{"i":"W0.7","k":"s","w":"W0","t":"REA core: agents, agreements, signatures, event envelope","pl":"The four-part foundation: people, agreements, signatures, and a tamper-evident history.","o":"agent","dep":["W0.6"],"dec":[],"v":"ci:db-verify","su":"agents, agreements, signatures exist per CIS \u00a706; shared event envelope (actor, occurred_at, prior_value) and audit trigger apply; pgTAP proves an UPDATE writes an audit row with prior value.","b":"The four REA primitives are the top-level partition; every relationship is an Event. Agreements carries versioning and content hash; Storage bucket policies mirror table RLS. The envelope DDL pattern is specified in docs/CONVENTIONS.md."},
{"i":"W0.8","k":"s","w":"W0","t":"role registry and access helpers","pl":"Write the fifteen roles from the bylaws and grant into the system.","o":"agent","dep":["W0.7","W0.5"],"dec":[],"v":"ci:rls-audit","su":"The 15 roles of CIS \u00a707 and Hub \u00a705 exist as data with source citations; helper functions (is_member, has_role, is_self) are used by all policies; claims reflect registry changes on next token refresh.","b":"Roles are defined by the bylaws and the grant, represented rather than invented. Role grants are events; SQL helpers marked stable for the planner; claims hook reads grants."},
{"i":"W0.9","k":"s","w":"W0","t":"edge functions scaffold and secrets boundary","pl":"A safe place for keys and any work the public site cannot do.","o":"agent","dep":["W0.3"],"dec":[],"v":"ci:functions-deploy","su":"Functions deploy from CI; a hello function verifies JWT and echoes the caller role; service-role key reachable only inside functions, asserted by a repo-wide secret-scan check.","b":"The only place secrets live at request time. Shared CORS, JWT verification middleware, deploy workflow; secret-scan joins required checks."},
{"i":"W0.10","k":"s","w":"W0","t":"scheduling rails and job registry","pl":"Two independent clocks, so scheduled work survives either one failing.","o":"agent","dep":["W0.9"],"dec":[],"v":"ci:db-verify + observed heartbeat rows","su":"pg_cron and an Actions cron each write a heartbeat job-run event; the jobs table shows both rails; a missed-run query exists.","b":"Two rails per the Reliability requirement (CIS \u00a714): an export scheduled from Actions still fires if the database scheduler is what failed. Enable pg_cron and pg_net; jobs and job_runs are events."},
{"i":"W0.11","k":"s","w":"W0","t":"email rail","pl":"Send official notices by email and record proof of delivery.","o":"agent","dep":["W0.9"],"dec":["D4"],"v":"ci:functions-deploy + human:operator (test send)","su":"email-send delivers via the D4 provider; provider webhooks write delivery events; a test notice shows queued, sent, delivered states on its record.","b":"Notices carry legally required timing and tracking (draft-bylaws \u00a72.4). Provider adapter interface so D4 stays swappable; build the adapter shape before D4 resolves, mark blocked on live sending only."},
{"i":"W0.12","k":"s","w":"W0","t":"portal scaffold and pages pipeline","pl":"Publish the member portal shell to the web.","o":"agent","dep":["W0.1"],"dec":["D1","D6"],"v":"ci:pages-deploy + ci:portal-build","su":"pages-deploy publishes on merge to main; the site serves 200 on the alpha domain with build SHA visible; SPA fallback works on a deep link; noindex present; anon key injected at build only.","b":"The member portal shell (CIS \u00a705, \u00a710). Custom subdomain, HTTPS, 404 fallback, meta CSP; the build fails if any non-public secret is referenced."},
{"i":"W0.13","k":"s","w":"W0","t":"design tokens and base components","pl":"Apply the cooperative typefaces, colors, and reading patterns.","o":"agent","dep":["W0.12"],"dec":[],"v":"human:Todd (reference page) + ci:portal-build","su":"Tokens match the canonical design-system file exactly (ground #0f0f0f, surface #1a1a1a, terracotta #c4956a and dims, light-mode ramp, 160ms/400ms durations); two-grammar type rule enforced; a rendered reference page passes visual review.","b":"Design-system adherence is a PRD requirement, not decoration (CIS \u00a710). Base primitives include the record detail three-part pattern: record, governing authority, history."},
{"i":"W0.14","k":"s","w":"W0","t":"export paths and tested restore","pl":"Every table exportable; restoring from backup is practiced, not assumed.","o":"agent","dep":["W0.10"],"dec":[],"v":"ci:db-verify (restore stage) + observed export artifacts","su":"docs/export-paths.md covers every existing table; a scheduled export writes open-format snapshots to Storage on both rails; a restore drill into a clean local database succeeds and is logged as a job run.","b":"The CR Phase 01 floor: every table ships with a documented export path; backup strategy survives any single vendor (CIS \u00a704)."},
{"i":"W0.15","k":"s","w":"W0","t":"chokepoint analysis as design artifact","pl":"Write down what happens if any vendor disappears.","o":"agent (draft) + human (adoption)","dep":["W0.1"],"dec":[],"v":"human:organizers","su":"docs/chokepoint-analysis.md covers Supabase, GitHub, the D4 provider, Mercury, Claude API, with failure modes, export paths, and the D5 trigger; adopted by organizer review on the PR.","b":"The PRD requires vendor selection recorded as an artifact, not folklore (CIS \u00a704). Clears the standing blocker that the analysis exist in writing. Draft from plan \u00a702; organizers adopt or amend."},
{"i":"W0.16","k":"s","w":"W0","t":"grammar lint","pl":"A guardrail keeping the wrong tax vocabulary out of our documents.","o":"agent","dep":["W0.1"],"dec":[],"v":"ci:grammar-lint","su":"CI fails on Subchapter T vocabulary (patronage dividend, written notice of allocation, per-unit retain) in migrations, UI strings, and docs of this repo, with a documented allowlist mechanism.","b":"The grammar quarantine: Subchapter K vocabulary only in RegenHub surfaces; patronage survives only as a scoped internal name. Word list and allowlist mechanics live in docs/CONVENTIONS.md."},
{"i":"W0.17","k":"s","w":"W0","t":"observability and error sink","pl":"When something breaks, it leaves a record we can read.","o":"agent","dep":["W0.9"],"dec":[],"v":"ci:functions-deploy + human:operator","su":"Client errors POST to an error-sink function and land in an admin-only events table; function logs reviewed in a runbook; a thrown test error is visible end to end.","b":"Audit by design extends to the system\u2019s own failures (principle 09)."},
{"i":"W0.18","k":"s","w":"W0","t":"build-status mirror","pl":"The portal shows the live progress of its own construction.","o":"agent","dep":["W0.2","W0.9","W0.12"],"dec":[],"v":"ci:status-mirror + human:Todd (panel)","su":"Every merge updates build_status in Supabase; the portal /build panel renders the ledger over Realtime within one refresh of merge.","b":"Near-real-time tracking, and the recursive case of legibility-as-product: the system shows its own construction to the members it is built for. The roadmap instrument becomes live here."},
{"i":"W1.1","k":"s","w":"W1","t":"memberships and class model","pl":"The member register, with the four classes and good standing.","o":"agent","dep":["W0.7","W0.8"],"dec":[],"v":"ci:rls-audit","su":"memberships per draft-bylaws \u00a71.1\u20131.4 with the four classes; good-standing as a derived view; \u00a718.1 scopes proven by probes (own-always, member-aggregate).","b":"The canonical register (CIS \u00a708). Statutory questions about non-voting classes remain with counsel and do not block representing the classes as data."},
{"i":"W1.2","k":"s","w":"W1","t":"stock ledger","pl":"One share per member, enforced by the database itself.","o":"agent","dep":["W1.1"],"dec":[],"v":"ci:db-verify","su":"stock_ledger enforces one Patron share per member at the database (unique partial constraint); issuance and transfer-back are events; pgTAP proves a second issuance fails.","b":"Conservation at the ledger (principle 05; draft-bylaws \u00a71.13). Preferred Stock exists in schema, reserved and inactive per the open investor framework (CIS \u00a717)."},
{"i":"W1.3","k":"s","w":"W1","t":"agreements repository, populated","pl":"Every governing document, versioned and openable by those it governs.","o":"agent","dep":["W0.7"],"dec":[],"v":"human:operator + ci:rls-audit","su":"Articles, draft bylaws, interim hub AUP, EE grant letter, membership-agreement template loaded as versioned, hashed records with correct visibility; a member can open what governs them from the portal.","b":"The shared repository both PRDs point at (CIS \u00a709b, Hub \u00a709b). Hashes anchor later attestation without committing to it (D8)."},
{"i":"W1.4","k":"s","w":"W1","t":"signature capture","pl":"Sign agreements in the portal; each signature is a recorded event.","o":"agent","dep":["W1.3","W0.5"],"dec":[],"v":"ci:db-verify + human:operator","su":"An authenticated signer executes an agreement version; the signature event stores signer, version hash, timestamp; the agreement detail view shows its signature history.","b":"Signatures are events under draft-bylaws \u00a71.4 (CIS \u00a706). Alpha scope is in-app click-to-sign with hash binding; external e-sign is an augmentation deliberately not taken, noted in the chokepoint doc."},
{"i":"W1.5","k":"s","w":"W1","t":"member directory and profile","pl":"A directory showing only what the bylaws require.","o":"agent","dep":["W1.1","W0.13"],"dec":[],"v":"human:Todd + ci:rls-audit","su":"Directory shows only what the bylaws require (P Phase 01 commitment); profile self-edit works; record detail follows the three-part pattern (record, governing authority, history).","b":"Traceability made visible (CIS \u00a710)."},
{"i":"W1.6","k":"s","w":"W1","t":"admission and onboarding workflow","pl":"The path from application to active member, step by step.","o":"agent","dep":["W1.2","W1.3","W1.4","W0.11"],"dec":["D2"],"v":"human:operator (walkthrough) + ci:db-verify","su":"The \u00a71.4 sequence runs end to end on synthetic data: application received, board decision recorded as a consent event, stock purchase recorded, agreements executed, orientation step, active status; each transition is an event with actor and citation.","b":"Named simplification: the board admission decision is recorded as a consent event rather than the full motions module (W4); the event shape is forward-compatible. The $100 stock purchase records an out-of-band payment reference in alpha."},
{"i":"W1.7","k":"s","w":"W1","t":"nou v1: read-only, grounded, logged","pl":"Nou answers questions with citations, and only sees what you can see.","o":"agent","dep":["W0.9","W1.1","W1.3"],"dec":[],"v":"ci:rls-audit (nou probes) + human:Todd","su":"Gateway forwards the invoking user JWT through a user-scoped client; answers cite section and record ids; every interaction logs prompt, citation set, response; a cross-member probe through Nou is refused identically to a direct query.","b":"CIS \u00a711 in its Phase 01 shape. Scoped impersonation is structural, not promised; the refusal posture holds. Interaction-log retention is an interim retain-all admin-only default, named as interim (CIS \u00a717)."},
{"i":"W1.8","k":"s","w":"W1","t":"notices v1","pl":"Notices that respect the bylaws timing windows.","o":"agent","dep":["W0.11","W1.1"],"dec":[],"v":"ci:db-verify + human:operator","su":"A notice with a draft-bylaws \u00a72.4 timing window is generated, sent, and shows confirmed delivery state on its record; the window computation is a tested pure function.","b":"Minimal legally timed notice path on the email rail."},
{"i":"W2.1","k":"s","w":"W2","t":"hub schema extensions","pl":"The hub twelve tables, each access rule citing the grant.","o":"agent","dep":["W0.6","W0.7","W0.8"],"dec":[],"v":"ci:rls-audit","su":"The twelve Hub \u00a704 tables exist with grant citations on every policy; hub roles enforce Hub \u00a705 scopes (applicant sees own application only; EE Liaison sees aggregates, not individuals); probes prove both.","b":"Greenfield surface; Stage 02 to 03 defaults from the first commit (Hub \u00a703)."},
{"i":"W2.2","k":"s","w":"W2","t":"application and access","pl":"A public application with published criteria and reasoned decisions.","o":"agent","dep":["W2.1","W0.12"],"dec":["D2"],"v":"ci:rls-audit (anon insert scope) + human:operator","su":"The public form submits through the D2 path under a narrowly scoped insert policy; selection criteria are versioned in the public repo; a decision is recorded against criteria and the applicant is notified with reason.","b":"Grant \u00a72 requires a public application and transparent, fair selection. The anonymous insert policy is the single deliberate hole in default-deny and carries its own probes; rate limiting via Edge Function wrapper is a named watch item."},
{"i":"W2.3","k":"s","w":"W2","t":"co-working sessions","pl":"Counting seat use against the grant promises.","o":"agent","dep":["W2.1"],"dec":[],"v":"human:operator + ci:db-verify","su":"Seat registry holds 10 weekly complimentary and 2\u20133 daily open seats as resources; session capture takes under a minute on mobile; seat_utilization_as_of derives purely from events.","b":"Surfaces directly into the KPI dashboard and monthly report (Hub \u00a706)."},
{"i":"W2.4","k":"s","w":"W2","t":"events module","pl":"Meetups and events, with attendance kept as counts, not name lists.","o":"agent","dep":["W2.1"],"dec":[],"v":"human:operator + ci:rls-audit","su":"Monthly Ethereum Meetup distinguishable from additional events; registration and attendance capture work; materials link to the educational surface; attendance aggregates without exposing names.","b":"Individual attendance records exist only with explicit opt-in (Hub \u00a703, privacy)."},
{"i":"W2.5","k":"s","w":"W2","t":"KPI and performance surface","pl":"The three grant KPIs computed from the record, with a public view.","o":"agent","dep":["W2.3","W2.4"],"dec":[],"v":"ci:db-verify (KPI fixtures) + human:Todd","su":"The three KPI views compute exactly per Hub \u00a707 (events per month at least 1; complimentary seats per ISO week at least 10; open seats per business day in 2\u20133); the public read-only view is live; every figure drills to the event rows that produced it.","b":"Computed rather than reported is the module whole point; the drill-down is the security posture the EE team can verify independently."},
{"i":"W2.6","k":"s","w":"W2","t":"impact reporting","pl":"Nou drafts the monthly report; a person approves; it publishes.","o":"agent","dep":["W2.5","W1.7"],"dec":[],"v":"human:organizer (first cycle) + ci:pages-deploy","su":"Nou drafts from the event log on the scheduled rail using the stable template (capacity, engagement, two to three highlights, needs); an organizer approves; the report publishes to a stable URL with a portable mirror copy.","b":"Hub \u00a707 template; augmentation, not automation."},
{"i":"W2.7","k":"s","w":"W2","t":"cross-pollination registry","pl":"A simple registry of aligned partner organizations.","o":"agent","dep":["W2.1"],"dec":[],"v":"human:operator","su":"partner_orgs and joint-event linkage work as the lightweight registry the PRD asks for (not a sales pipeline); visible to members.","b":"Hub \u00a706."},
{"i":"W2.8","k":"s","w":"W2","t":"educational surface","pl":"Learning materials and opportunity listings on the public hub page.","o":"agent","dep":["W2.1","W0.12"],"dec":[],"v":"human:operator","su":"Displays, materials, and opportunity listings render on the public hub page; currency and rotation status tracked; EE-provided materials versioned alongside local ones.","b":"Every visual and narrative element doubles as a learning touchpoint (grant \u00a72)."},
{"i":"W2.9","k":"s","w":"W2","t":"grant lifecycle","pl":"Tracking the grant tranches and milestones against the agreement.","o":"agent","dep":["W2.5","W1.3"],"dec":["D9"],"v":"human:organizer","su":"Tranches and milestones from Hub \u00a708 exist as events against the grant agreement record; the compliance view shows KPI history in the form D9 selects; tranche entries reference treasury once W3 lands.","b":"Hub \u00a708."},
{"i":"W3.0","k":"s","w":"W3","t":"author the capital wave briefs","pl":"Write the full work briefs for the capital wave.","o":"agent","dep":["W1"],"dec":[],"v":"ci:milestone-validate","su":"W3.1\u2013W3.7 exist as schema-complete milestone files.","b":"Detail is produced at the boundary where it is real rather than invented early. Coarse edge: wave W3 follows wave W1. The wave-boundary authoring guide (collection item C10) governs how."},
{"i":"W3.1","k":"s","w":"W3","t":"capital accounts and capital events","pl":"Member capital accounts with double-entry history.","o":"agent","dep":["W3.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W3.0).","b":"Double-entry capital_events with book/tax distinction and balance-conservation tests (draft-bylaws \u00a75.1)."},
{"i":"W3.2","k":"s","w":"W3","t":"personal balance view","pl":"Each member sees their own balance and its full history.","o":"agent","dep":["W3.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W3.0).","b":"Per the member success criteria (CIS \u00a715)."},
{"i":"W3.3","k":"s","w":"W3","t":"manual allocation against the equal default","pl":"Allocations entered by hand until the bylaws ratify a formula.","o":"agent","dep":["W3.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W3.0).","b":"Formula automation explicitly gated on R1 (CIS \u00a717)."},
{"i":"W3.4","k":"s","w":"W3","t":"mercury read-only ingestion","pl":"Bank transactions flow in read-only; the bank is never the record.","o":"agent","dep":["W3.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W3.0).","b":"Scheduled rails; hub-expenditure tagging at the transaction level (Hub \u00a709c); treasury as payment rail, never record (CR Phase 02)."},
{"i":"W3.5","k":"s","w":"W3","t":"tax records and K-1 preparation","pl":"Tax records encrypted, administrator-only, feeding the accountant.","o":"agent","dep":["W3.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W3.0).","b":"Encrypted identifiers; K-1 preparation export (CIS \u00a708)."},
{"i":"W3.6","k":"s","w":"W3","t":"treasury views and distribution shape","pl":"Treasury views and distributions; multi-sig stays a human act.","o":"agent","dep":["W3.0"],"dec":["D10"],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W3.0).","b":"Multi-sig named as a banking-structure action owned by humans, not code (S Phase 02). D10 blocks the facility-obligation detail only."},
{"i":"W3.7","k":"s","w":"W3","t":"grant tranches joined to treasury","pl":"Grant tranches joined to the treasury record.","o":"agent","dep":["W3.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W3.0).","b":"Joins W2.9 grant lifecycle entries to treasury."},
{"i":"W4.0","k":"s","w":"W4","t":"author the governance wave briefs","pl":"Write the full work briefs for the governance wave.","o":"agent","dep":["W3"],"dec":[],"v":"ci:milestone-validate","su":"W4.1\u2013W4.7 exist as schema-complete milestone files.","b":"Coarse edge: wave W4 follows wave W3. Activation of binding electronic votes is gated on R1 semantics being final."},
{"i":"W4.1","k":"s","w":"W4","t":"meetings, attendance, proxies, quorum","pl":"Meetings with quorum computed live and the rule shown.","o":"agent","dep":["W4.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W4.0).","b":"Quorum always correct and the underlying rule shown (CIS \u00a715)."},
{"i":"W4.2","k":"s","w":"W4","t":"motions and immutable votes","pl":"Motions and votes that cannot be altered once cast.","o":"agent","dep":["W4.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W4.0).","b":"Thresholds enforced as constraints."},
{"i":"W4.3","k":"s","w":"W4","t":"consents","pl":"Decisions taken by written consent, recorded properly.","o":"agent","dep":["W4.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W4.0).","b":"draft-bylaws \u00a72.8, \u00a73.15."},
{"i":"W4.4","k":"s","w":"W4","t":"minutes drafting and ratification","pl":"Nou drafts minutes; the Secretary ratifies.","o":"agent","dep":["W4.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W4.0).","b":"Augmentation, not automation: the Secretary act remains the authoritative one."},
{"i":"W4.5","k":"s","w":"W4","t":"notices v2: receipt hardening","pl":"Stronger proof that official notices arrived.","o":"agent","dep":["W4.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W4.0).","b":"Receipt confirmation hardening toward the Phase 03 posture."},
{"i":"W4.6","k":"s","w":"W4","t":"voting interface, open-source","pl":"The voting screen itself, published as open source.","o":"agent","dep":["W4.0"],"dec":[],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W4.0).","b":"O-pathway Phase 03 commitment."},
{"i":"W4.7","k":"s","w":"W4","t":"attestation extension (optional)","pl":"Optionally anchoring vote records on-chain.","o":"agent","dep":["W4.0"],"dec":["D8"],"v":"to be authored","seeded":1,"su":"Brief and success state authored at the wave boundary (W4.0).","b":"Blocked on D8 attestation scope and key custody."},
{"i":"W5.0","k":"s","w":"W5","t":"author the lifecycle wave briefs","pl":"Write the briefs for withdrawal, suspension, termination, and redemption.","o":"agent","dep":["W4"],"dec":[],"v":"ci:milestone-validate","su":"Lifecycle wave milestone files exist, schema-complete.","b":"Seeded scope: the membership state machine with signed, logged transitions; withdrawal with the fourteen-day notice and equity calculation; suspension clock; termination hearing support; redemption schedules up to five years, with the simplification path noted if the non-redeemable option is adopted (CIS \u00a717, draft-bylaws \u00a71.9.3)."},
{"i":"W6.0","k":"s","w":"W6","t":"author the full-interface wave briefs","pl":"Write the briefs for analytics, the benefit report, member export, and the walkaway drill.","o":"agent","dep":["W5"],"dec":[],"v":"ci:milestone-validate","su":"Full-interface wave milestone files exist, schema-complete.","b":"Seeded scope: derived analytics; benefit report generation and the guaranteed public view anchoring the O pathway (draft-bylaws \u00a7XV); audit support surface; member-exercisable data export from the portal (CR Phase 04); the walkaway drill as a tested, scheduled capability (CR Phase 05), building on W0.14."},
{"i":"P1","k":"p","w":"P","t":"practice (CIS Phase 06)","pl":"The culture work no software can ship.","o":"membership","dep":["W6"],"dec":[],"v":"lived, not shipped","su":"Portable formats by habit; build-in-public reflexive; need-to-know felt instinct; security hygiene habitual.","b":"Deliberately not a development phase (CIS \u00a716). Indexed so the board never reads complete on architecture alone."},
]

G1 = {"i":"G1","k":"g","w":"G","t":"alpha gate","pl":"The bar the alpha must clear before real members rely on it.","o":"composite","v":"composite",
 "steps":["W0.1","W0.2","W0.3","W0.4","W0.5","W0.6","W0.7","W0.8","W0.9","W0.10","W0.11","W0.12","W0.13","W0.14","W0.15","W0.16","W0.17","W0.18","W1.1","W1.2","W1.3","W1.4","W1.5","W1.6","W1.7","W1.8","W2.1","W2.2","W2.3","W2.4","W2.5","W2.6"],
 "decs":["D1","D2","D3","D4","D6","D7"],
 "su":"Every required step and decision verified.",
 "b":"Operationally, G1 means: a real invited member can sign in, see what governs them, sign their agreement, appear in the directory, ask Nou a grounded question and get a cited answer; and the Hub team can run applications, sessions, events, the KPI dashboard, and a monthly report against production data. W2.7\u2013W2.9 and all of W3 onward proceed against the same ledger after the gate."}

def slug(t):
    s = re.sub(r"[^a-z0-9]+", "-", t.lower()).strip("-")
    return s[:46].rstrip("-")

def ylist(xs):
    return "[" + ", ".join(xs) + "]"

def fm(lines):
    return "---\n" + "\n".join(lines) + "\n---\n"

def write(path, content):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)

def milestone_file(x):
    lines = [
        f"id: {x['i']}",
        f"title: \"{x['t']}\"",
        f"wave: {x['w']}",
        f"kind: {KIND[x['k']]}",
        f"owner: \"{x['o']}\"",
        "status: pending",
        f"detail: {'seeded' if x.get('seeded') else 'briefed'}",
        f"depends_on: {ylist(x.get('dep', []))}",
        f"decision_refs: {ylist(x.get('dec', []))}",
    ]
    if x.get("act"):
        lines.append(f"activates: {ylist(x['act'])}")
    lines += [
        "success_state: >-",
        f"  {x['su']}",
        f"verification: \"{x['v']}\"",
    ]
    body = []
    body.append("## Brief\n")
    body.append(x["b"] + "\n")
    body.append("## Plain language\n")
    body.append(x["pl"] + "\n")
    if x.get("seeded"):
        body.append("## Note\n")
        body.append("This entry is seeded at summary level. Its full brief, fine-grained dependencies, and testable success state are authored at the wave boundary step and must pass ci:milestone-validate before work begins.\n")
    if x["k"] == "d":
        body.append("## Record\n")
        body.append(f"The deliberation brief and the eventual record of decision live at docs/decisions/{x['i']}.md. This ledger entry tracks status only; agents never set it.\n")
    return fm(lines) + "\n" + "\n".join(body)

def gate_file(g):
    lines = [
        f"id: {g['i']}",
        f"title: \"{g['t']}\"",
        f"wave: {g['w']}",
        "kind: gate",
        f"owner: \"{g['o']}\"",
        "status: pending",
        "detail: briefed",
        "depends_on: []",
        "decision_refs: []",
        f"requires_steps: {ylist(g['steps'])}",
        f"requires_decisions: {ylist(g['decs'])}",
        "success_state: >-",
        f"  {g['su']}",
        f"verification: \"{g['v']}\"",
    ]
    body = "## Brief\n\n" + g["b"] + "\n\n## Plain language\n\n" + g["pl"] + "\n"
    return fm(lines) + "\n" + body

def decision_record(x):
    lines = [
        f"id: {x['i']}",
        f"title: \"{x['t']}\"",
        "status: open",
        f"owner: \"{x['o']}\"",
        f"ledger_entry: milestones/{x['w']}/{x['i']}-{slug(x['t'])}.md",
    ]
    body = [
        "## Question\n", x["pl"] + "\n",
        "## Context and options\n", x["b"] + "\n",
        "## Proposed default\n",
        "Stated in the context above; a proposal only. The decision is reserved to the named owner.\n",
        "## Record of decision\n",
        "_Open. When decided: record the choice, the date, who decided, and one paragraph of reasoning. Flip status to decided in the front matter and update the ledger entry status in the same PR._\n",
    ]
    return fm(lines) + "\n" + "\n".join(body)

def main():
    count = 0
    for x in L:
        p = f"milestones/{x['w']}/{x['i']}-{slug(x['t'])}.md"
        write(p, milestone_file(x))
        count += 1
        if x["k"] in ("d", "r"):
            write(f"docs/decisions/{x['i']}.md", decision_record(x))
    write(f"milestones/G/G1-{slug(G1['t'])}.md", gate_file(G1))
    count += 1
    print(f"wrote {count} milestone files + {sum(1 for x in L if x['k'] in ('d','r'))} decision records")

if __name__ == "__main__":
    main()
